version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  core_service:
    build: ./core_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=sqlite:///./app/pysis.db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./core_service:/app
    networks:
      - app_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload

