version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    networks:
      - app_network
    depends_on:
      - channel_service

  core_service:
    build: ./core_service
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    networks:
      - app_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    restart: unless-stopped

  channel_service:
    build: ./channel_service
    environment:
      - CORE_SERVICE_URL=http://core_service:8002
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - ORG_ID=1
    depends_on:
      - core_service
    volumes:
      - ./channel_service:/app
    networks:
      - app_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload
    restart: unless-stopped

  statistics_service:
    build: ./statistics_service
    ports:
      - "8004:8004"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./statistics_service:/app
      - ./core_service/app:/data:ro
    depends_on:
      - core_service
    networks:
      - app_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8004 --reload
    restart: unless-stopped

volumes:
  caddy_data:
